name: CI
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    env:
        app-name: hello_${{matrix.os}}.o
    steps:
      - uses: actions/checkout@v3
      
      - name: build cpp
        run: g++ hello.cpp -o ${{env.app-name}}

      - name: Run cpp app
        run: ./${{env.app-name}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: cpp app
          path: ${{env.app-name}}
          retention-days: 1
