name: CI
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        gcc-vars: [-O0, -O3]
    runs-on: ${{matrix.os}}
    env:
        app-name: hello_${{matrix.os}}.o
    steps:
      - uses: actions/checkout@v3
      
      - name: build cpp
        run: g++ hello.cpp -o ${{env.app-name}} ${{matrix.gcc-vars}}

      - name: Run cpp app
        run: ./${{env.app-name}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: cpp app
          path: ${{env.app-name}}
          retention-days: 1
          
          
  sentMessage:
   name: Build
   runs-on: ubuntu-latest
   steps:
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: 988799349
        token: 6199017139:AAFS39-3_DAwZ0883dkXjM5ZM6qwqG4AVLs
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
