name: CI
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      
      - name: build cpp
        run: g++ hello.cpp -o hello_${{runner.OS}}.o

      - name: Run cpp app
        run: ./hello_${{runner.OS}}.o

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: cpp app
          path: hello_${{runner.OS}}.o
          retention-days: 1
