name: CI
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: build cpp
        run: g++ hello.cpp -o hello.o

      - name: Run cpp app
        run: ./hello.o

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: cpp app ubuntu
          path: hello.o
          retention-days: 1
          
  build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
      
        - name: build cpp
          run: g++ hello.cpp -o hello.o

        - name: Run cpp app
          run: ./hello.o

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with: 
            name: cpp app macos
            path: hello.o
            retention-days: 1

